DWAPlannerROS:
  publish_traj_pc: true
  publish_cost_grid_pc: true
  max_vel_x: 1
  min_vel_x: -0.3
  max_vel_theta: 1
  min_vel_theta: -0.3
  min_in_place_vel_theta: 1
  controller_frequency: 10
  planner_frequency: 3.0
  controller_patience: 3.0
  planner_patience: 5.0
  transform_tolerance: 1.0
  acc_lim_theta: 8
  acc_lim_x: 3
  acc_lim_y: 3

  holonomic_robot: false
