obstacle_range: 0.8
raytrace_range: 8.0
footprint: [[-0.55, -0.575], [0.55, -0.575], [0.55, 0.575], [-0.55, 0.575]]
inflation_radius: 0.2

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor:
  sensor_frame: laser_frame
  data_type: LaserScan
  topic: scan_filtered
  marking: true
  clearing: true

point_cloud_sensor:
  sensor_frame: camera_depth_frame
  data_type: PointCloud2
  topic: cloud
  marking: true
  clearing: true

obstacle_layer:
  clearing: true
  track_unknown_space: true
  combination_method: 1

inflation_layer:
  inflation_radius: 0.2

static_layer:
  map_topic: map
  subscribe_to_updates: true

costmap_2d:
  plugins:
    - { name: "obstacle_layer", type: "costmap_2d::ObstacleLayer" }
    - { name: "inflation_layer", type: "costmap_2d::InflationLayer" }
    - { name: "static_layer", type: "costmap_2d::StaticLayer" }
