global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 3.0
  static_map: false
  resolution: 0.05

  plugins:
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    sensor_frame: laser_frame   # Name of the laser sensor frame
    data_type: LaserScan
    topic: scan_filtered                    
    marking: true
    clearing: true               
    max_obstacle_height: 2.0        # for vertical filtering
    obstacle_range: 1             # how far to *mark* obstacles
    raytrace_range: 8             # how far to *clear* obstacles

inflation_layer:
  inflation_radius: 0.5

obstacle_range: 1
raytrace_range: 8.0
